sudo: required

language: node_js

node_js:
  - "5.8.0"

services:
  - docker

before_install:
  - docker build -t adarshkkumar/gocd-monitor .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push adarshkkumar/gocd-monitor;
    fi